apiVersion: skaffold/v2beta11
kind: Config

deploy: {}

profiles:
- name: istio
  deploy:
    kustomize:
      paths:
      - "istio/"  
- name: contour
  deploy:
    kustomize:
      paths:
      - "contour/"
- name: argocd
  deploy:
    kubectl:
      manifests:
      - "argocd/namespace.yaml"
      - "argocd/argocd.yaml"
      defaultNamespace: argocd
    kustomize:
      paths:
      - "argocd/image-updater"
      defaultNamespace: argocd
- name: smallstep-ca
  deploy:
    helm:
      releases:
        - name: "step-certificates"
          chartPath: "smallstep/step-certificates"
          remote: true
          upgradeOnChange: true
          valuesFiles:
            - "smallstep/values.yaml"
