apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: oauth2-proxy  
spec:
  hosts:
  - "api.shipperizer.org"
  gateways:
  - istio-system/gateway
  http:
  - match:
    - uri:
        prefix: /oauth2/callback
    route:
    - destination:   
        host: oauth2-proxy
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: oauth2-proxy
spec:
  host: oauth2-proxy
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN   