apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-shipperizer-org
  namespace: istio-system
spec:
  dnsNames:
  - api.shipperizer.org
  duration: 1440h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: http-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 24h0m0s
  secretName: api-shipperizer-org-tls