apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 40443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: api-shipperizer-org-tls # This should match the Certificate secretName
    hosts:
    - "api.shipperizer.org"    
  - port:
      number: 40080
      name: http
      protocol: HTTP
    hosts:
    - "api.shipperizer.org"  